### ISSUE TITLE
_network_image_io.dart

### ISSUE THREAD

**Issue by ayzek67** [nirala96/Flutter-News-App#2]
Hi
I could not solve the error, I would be very happy if you help me.

'package:flutter/src/painting/_network_image_io.dart': Failed assertion: line 25 pos 11: 'url != null': is not true.

/// The dart:io implementation of [image_provider.NetworkImage].
@immutable
class NetworkImage extends image_provider.ImageProvider<image_provider.NetworkImage> implements image_provider.NetworkImage {
  /// Creates an object that fetches the image at the given URL.
  ///
  /// The arguments [url] and [scale] must not be null.
  const NetworkImage(this.url, { this.scale = 1.0, this.headers })
  :assert(url != null ),
  assert(scale != null);

@override
  final String url;

  @override
  final double scale;

  @override
  final Map<String, String>? headers;

  @override
  Future<NetworkImage> obtainKey(image_provider.ImageConfiguration configuration) {
    return SynchronousFuture<NetworkImage>(this);
  }

  @override
  ImageStreamCompleter load(image_provider.NetworkImage key, image_provider.DecoderCallback decode) {
    // Ownership of this controller is handed off to [_loadAsync]; it is that
    // method's responsibility to close the controller's stream when the image
    // has been loaded or an error is thrown.
    final StreamController<ImageChunkEvent> chunkEvents = StreamController<ImageChunkEvent>();

    return MultiFrameImageStreamCompleter(
      codec: _loadAsync(key as NetworkImage, chunkEvents, decode),
      chunkEvents: chunkEvents.stream,
      scale: key.scale,
      debugLabel: key.url,
      informationCollector: () {
        return <DiagnosticsNode>[
          DiagnosticsProperty<image_provider.ImageProvider>('Image provider', this),
          DiagnosticsProperty<image_provider.NetworkImage>('Image key', key),
        ];
      },
    );
  }

  // Do not access this field directly; use [_httpClient] instead.
  // We set `autoUncompress` to false to ensure that we can trust the value of
  // the `Content-Length` HTTP header. We automatically uncompress the content
  // in our call to [consolidateHttpClientResponseBytes].
  static final HttpClient _sharedHttpClient = HttpClient()..autoUncompress = false;

  static HttpClient get _httpClient {
    HttpClient client = _sharedHttpClient;
    assert(() {
      if (debugNetworkImageHttpClientProvider != null)
        client = debugNetworkImageHttpClientProvider!();
      return true;
    }());
    return client;
  }

  Future<ui.Codec> _loadAsync(
    NetworkImage key,
    StreamController<ImageChunkEvent> chunkEvents,
    image_provider.DecoderCallback decode,
  ) async {
    try {
      assert(key == this);

      final Uri resolved = Uri.base.resolve(key.url);

      final HttpClientRequest request = await _httpClient.getUrl(resolved);

      headers?.forEach((String name, String value) {
        request.headers.add(name, value);
      });
      final HttpClientResponse response = await request.close();
      if (response.statusCode != HttpStatus.ok) {
        // The network may be only temporarily unavailable, or the file will be
        // added on the server later. Avoid having future calls to resolve
        // fail to check the network again.
        await response.drain<List<int>>();
        throw image_provider.NetworkImageLoadException(statusCode: response.statusCode, uri: resolved);
      }

      final Uint8List bytes = await consolidateHttpClientResponseBytes(
        response,
        onBytesReceived: (int cumulative, int? total) {
          chunkEvents.add(ImageChunkEvent(
            cumulativeBytesLoaded: cumulative,
            expectedTotalBytes: total,
          ));
        },
      );
      if (bytes.lengthInBytes == 0)
        throw Exception('NetworkImage is an empty file: $resolved');

      return decode(bytes);
    } catch (e) {
      // Depending on where the exception was thrown, the image cache may not
      // have had a chance to track the key in the cache at all.
      // Schedule a microtask to give the cache a chance to add the key.
      scheduleMicrotask(() {
        PaintingBinding.instance!.imageCache!.evict(key);
      });
      rethrow;
    } finally {
      chunkEvents.close();
    }
  }

  @override
  bool operator ==(Object other) {
    if (other.runtimeType != runtimeType)
      return false;
    return other is NetworkImage
        && other.url == url
        && other.scale == scale;
  }

  @override
  int get hashCode => ui.hashValues(url, scale);

  @override
  String toString() => '${objectRuntimeType(this, 'NetworkImage')}("$url", scale: $scale)';
}

**Comment by nirala96** [comment]
Yes sure i will help you....its 1:46 pm here...tommorow sure i will get
back to you

**Comment by nirala96** [comment]
have you make your own API key from newsapi.org?

**Comment by ayzek67** [comment]
Thank you bro. Now I created the api. No more problems. I am sorry for my
late answer.

Arunoday kumar ***@***.***>, 11 Eyl 2021 Cmt, 22:47 tarihinde
şunu yazdı:

> have you make your own API key from newsapi.org?
>
>
> On Sat, Sep 11, 2021 at 1:47 AM 201951031 ARUNODAY KUMAR <

**Comment by ayzek67** [comment]
[image: 2 app.jpg]
[image: 3 app.jpg]
sorry sorry. I created api myself. but still same problem.

Lapira ***@***.***>, 13 Eyl 2021 Pzt, 01:40 tarihinde şunu yazdı:

> Thank you bro. Now I created the api. No more problems. I am sorry for my
> late answer.
>
> Arunoday kumar ***@***.***>, 11 Eyl 2021 Cmt, 22:47
> tarihinde şunu yazdı:
>
>> have you make your own API key from newsapi.org?
>>
>>
>> On Sat, Sep 11, 2021 at 1:47 AM 201951031 ARUNODAY KUMAR <

**Comment by ayzek67** [comment]
My generated api;


class AppStrings {
  static String url =
      "https://newsapi.org/v2/everything?q=bitcoin&sortBy=publishedAt&apiKey=22504163f0cc45d98c69fb854e038612#";
}


Lapira ***@***.***>, 13 Eyl 2021 Pzt, 02:31 tarihinde şunu yazdı:

> [image: 2 app.jpg]
> [image: 3 app.jpg]
> sorry sorry. I created api myself. but still same problem.
>
> Lapira ***@***.***>, 13 Eyl 2021 Pzt, 01:40 tarihinde şunu yazdı:
>
>> Thank you bro. Now I created the api. No more problems. I am sorry for my
>> late answer.
>>
>> Arunoday kumar ***@***.***>, 11 Eyl 2021 Cmt, 22:47
>> tarihinde şunu yazdı:
>>
>>> have you make your own API key from newsapi.org?
>>>
>>>
>>> On Sat, Sep 11, 2021 at 1:47 AM 201951031 ARUNODAY KUMAR <

**Comment by nirala96** [comment]
Can you share the error logs...not able to view the images.
And try not to expose your API KEYs on public platform, it may cause harm

**Comment by ayzek67** [comment]
Hi;

Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1.917ms.

======== Exception caught by widgets library
=======================================================
The following _CastError was thrown building BlocListener<ArticleBloc,
ArticleState>(dirty, state: _BlocListenerBaseState<ArticleBloc,
ArticleState>#f262e):
Null check operator used on a null value

The relevant error-causing widget was:
  BlocListener<ArticleBloc, ArticleState>
file:///C:/flutterSDK/.pub-cache/hosted/
pub.dartlang.org/flutter_bloc-7.2.0/lib/src/bloc_builder.dart:158:12
When the exception was thrown, this was the stack:
#0      _BlocListenerBaseState.buildWithChild
(package:flutter_bloc/src/bloc_listener.dart:185:17)
#1      SingleChildState.build (package:nested/nested.dart:317:41)
#2      StatefulElement.build
(package:flutter/src/widgets/framework.dart:4691:27)
#3      SingleChildStatefulElement.build (package:nested/nested.dart:339:18)
#4      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4574:15)
...
====================================================================================================

======== Exception caught by widgets library
=======================================================
The following assertion was thrown building:
'package:flutter/src/painting/_network_image_io.dart': Failed assertion:
line 26 pos 12: 'url != null': is not true.


Either the assertion indicates an error in the framework itself, or we
should provide substantially more information in this error message to help
you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      new NetworkImage
(package:flutter/src/painting/_network_image_io.dart:26:12)
#3      new Image.network (package:flutter/src/widgets/image.dart:404:68)
#4      _HomePageState.buildArticleList.<anonymous closure>
(package:coinnews/views/home_page.dart:114:34)
#5      SliverChildBuilderDelegate.build
(package:flutter/src/widgets/sliver.dart:455:22)
#6      SliverMultiBoxAdaptorElement._build
(package:flutter/src/widgets/sliver.dart:1213:28)
...
====================================================================================================

Arunoday kumar ***@***.***>, 13 Eyl 2021 Pzt, 06:09 tarihinde
şunu yazdı:

**Comment by nirala96** [comment]
can you share the link of your code repo, as i think you have added new files ('package:flutter/src/painting/_network_image_io.dart') which i am unable to find
